{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "timecamp-scim.fullname" . }}-secrets
  labels:
    {{- include "timecamp-scim.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "timecamp-scim.fullname" . }}-gcpsm
    kind: SecretStore
  target:
    name: {{ include "timecamp-scim.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    # TimeCamp secrets
    - secretKey: TIMECAMP_API_KEY
      remoteRef:
        key: timecamp-scim-secrets
        property: TIMECAMP_API_KEY
    # BambooHR secrets
    - secretKey: BAMBOOHR_API_KEY
      remoteRef:
        key: timecamp-scim-secrets
        property: BAMBOOHR_API_KEY
    # Azure AD secrets
    - secretKey: AZURE_CLIENT_SECRET
      remoteRef:
        key: timecamp-scim-secrets
        property: AZURE_CLIENT_SECRET
    - secretKey: AZURE_BEARER_TOKEN
      remoteRef:
        key: timecamp-scim-secrets
        property: AZURE_BEARER_TOKEN
    - secretKey: AZURE_REFRESH_TOKEN
      remoteRef:
        key: timecamp-scim-secrets
        property: AZURE_REFRESH_TOKEN
    # LDAP secrets
    - secretKey: LDAP_PASSWORD
      remoteRef:
        key: timecamp-scim-secrets
        property: LDAP_PASSWORD
    # FactorialHR secrets
    - secretKey: FACTORIAL_API_KEY
      remoteRef:
        key: timecamp-scim-secrets
        property: FACTORIAL_API_KEY
    # S3 credentials
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: timecamp-scim-secrets
        property: S3_ACCESS_KEY_ID
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: timecamp-scim-secrets
        property: S3_SECRET_ACCESS_KEY
{{- end }}