{{- if .Values.jobs.removeEmptyGroups.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "timecamp-scim.fullname" . }}-remove-empty-groups
  labels:
    {{- include "timecamp-scim.labels" . | nindent 4 }}
    app.kubernetes.io/component: remove-empty-groups
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "timecamp-scim.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: remove-empty-groups
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "timecamp-scim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.jobs.removeEmptyGroups.command | toJson }}
          env:
            {{- include "timecamp-scim.commonEnv" . | nindent 12 }}
            {{- include "timecamp-scim.secretEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}