{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "timecamp-scim.fullname" . }}-gcpsm
  labels:
    {{- include "timecamp-scim.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.secretStore.projectID | quote }}
      {{- if .Values.externalSecrets.secretStore.auth.workloadIdentity }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.secretStore.auth.workloadIdentity.clusterLocation }}
          clusterName: {{ .Values.externalSecrets.secretStore.auth.workloadIdentity.clusterName }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.secretStore.auth.workloadIdentity.serviceAccountRef.name | default (include "timecamp-scim.serviceAccountName" .) }}
      {{- end }}
{{- end }}